a = input('Digite alguma coisa: ')
print('o tipo primitivo de {} '.format(a), type(a))
print('So tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfa numerico? ', a.isalnum())
print('É alfabetico? ', a.isalpha())
print('É decimal? ', a.isdecimal())
print('Esta somente em letras minisculas? ', a.islower())
print('Esta somente em maiusculas? ', a.isupper())
